version: '3.9'
services:   
   #docker ui
   portainer:
      #基于Alpine Linux版本
      image: portainer/portainer-ce:2.9.3-alpine
      container_name: portainer
      restart: always
      ports: 
         - 9000:9000
      volumes: 
         - /var/run/docker.sock:/var/run/docker.sock